version: '3.9'
services:
   node1:
      build: ./node
      command: python3 ./main.py
      ports:
         - 8080:1234

   node2:
      build: ./node
      command: python3 ./main.py
      ports:
         - 8081:1234

   node3:
      build: ./node
      command: python3 ./main.py
      ports:
         - 8082:1234

   node4:
      build: ./node
      command: python3 ./main.py
      ports:
         - 8083:1234