version: '3.9'
services:
   node1:
      build: ./node
      command: python3 ./main.py
      expose:
         - 1234
      volumes: 
         - ./Node1:/files


   node2:
      build: ./node
      command: python3 ./main.py
      expose:
         - 1234
      volumes: 
         - ./Node2:/files

   node3:
      build: ./node
      command: python3 ./main.py
      expose:
         - 1234
      volumes: 
         - ./Node3:/files

   node4:
      build: ./node
      command: python3 ./main.py
      expose:
         - 1234
      volumes: 
         - ./Node4:/files