services:
   node 1:
      build: .
      command: python ./main.py
      ports:
         - 65400:65432
         - 65401:65432
      volumes:
         - ./node1:/files

   node 2:
      build: .
      command: python ./main.py
      ports:
         - 65402:65432
         - 65403:65432
      volumes:
         - ./node2:/files

   node 3:
      build: .
      command: python ./main.py
      ports:
         - 65404:65432
         - 65405:65432
      volumes:
         - ./node3:/files

   node 4:
      build: .
      command: python ./main.py
      expose:
         ports:
         - 65406:65432
         - 65407:65432
      volumes:
         - ./node4:/files

networks:
   default:
      ipam:
         config:
            - subnet: 192.168.0.0/24
              gateway: 192.168.0.1